[package]
name = "orcestrator"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deep_space = {git = "https://github.com/althea-net/deep_space/"}
contact = {git = "https://github.com/althea-net/contact"}
# deep_space = {path = "../../deep_space"}
# contact = {path = "../../contact"}
serde_derive = "1.0"
clarity = "0.1"
docopt = "1"
serde = "1.0"
actix-web = {version = "2.0", features=["openssl"]}
actix-rt = "1"
lazy_static = "1"
url = "2"
web30 = {git = "https://github.com/althea-net/web30"}
num256 = "0.2"